name: ci
on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pipery-dev/pipery-java-ci@v1
        with:
          project_path: .
          java_version: 21
          build_tool: auto
          tests_path: 
          registry: ghcr.io
          version_bump: patch
          log_file: pipery.jsonl
          skip_sast: false
          skip_sca: false
          skip_lint: false
          skip_build: false
          skip_test: false
          skip_versioning: false
          skip_packaging: false
          skip_release: false
          skip_reintegration: false
          target_branch: main